### ISSUE TITLE
Android inapp billing v3 is not working (1.1.0)

### ISSUE THREAD

**Issue by danieljr99048** [anjlab/android-inapp-billing-v3#488] opened 2021-04-28 15:32 UTC
It does not comply with the new Google Play policy 2021, after November goodbye.

update as soon as possible as many developers use.

**Comment by wicaodian** [comment] 2021-04-29 09:55
Duplicate of #478

**Comment by Duna** [comment] 2021-05-04 22:18
V3 my ass, this is v2

**Comment by Cand3h** [comment] 2021-05-08 16:44
Any idea what to do? It seems that there won't be any update.

**Comment by Duna** [comment] 2021-05-08 17:59
I did switch to google play purchase V3. It's pretty similar to this lib.

**Comment by serggl** [comment] 2021-10-29 19:09
Library was upgraded. See https://github.com/anjlab/android-inapp-billing-v3/pull/497

**Closed by serggl** 2021-10-29 19:09 UTC

**Comment by Duna** [comment] 2021-10-30 21:34
Good work 👍 thanks
