### ISSUE TITLE
We've detected that this app is using an old version of Google Play Billing. From 1 November 2021, all app updates must use Billing Library version 3 or newer.

### ISSUE THREAD

**Issue by Dhaval990** [anjlab/android-inapp-billing-v3#486] opened 2021-04-16 16:33 UTC
I am getting this message in the play store.

We've detected that this app is using an old version of Google Play Billing. From 1 November 2021, all app updates must use Billing Library version 3 or newer.

Action required: Please verify that your publicly available APKs are updated to the latest version of the Play Billing Library. This includes any APK or App Bundle rolled out in production.

**Comment by ashutoshgngwr** [comment] 2021-04-25 11:28
Duplicate of #478

**Comment by Cand3h** [comment] 2021-05-08 16:44
Any idea what to do? It seems that there won't be any update.

**Comment by moisoni97** [comment] 2021-06-18 21:43
Check my library which uses `google billing v4`, it is very simple to use.
https://github.com/moisoni97/google-inapp-billing

**Comment by deirputraid** [comment] 2021-08-09 10:22
**This is the old version**... I keep getting a warning when uploading the app to the console

**Comment by serggl** [comment] 2021-10-29 19:09
Library was upgraded. See https://github.com/anjlab/android-inapp-billing-v3/pull/497

**Closed by serggl** 2021-10-29 19:09 UTC

**Comment by sangolariel** [comment] 2021-11-22 08:38
+1

**Comment by CodeProf14** [comment] 2022-09-04 13:55
Problem fixed here : https://youtu.be/SBXEgAZDnFM
