### ISSUE TITLE
Confirmation about google policy for billing in 3.0

### ISSUE THREAD

**Issue by najam-amfnrh9** [anjlab/android-inapp-billing-v3#485] opened 2021-04-13 09:46 UTC
I have concerns about will this support google latest requirement::: 
Reminder: Starting on August 2, 2021, all new apps must use Billing Library version 3 or newer. By November 1, 2021, all updates to existing apps must use Billing Library version 3 or newer. 
Reference: https://developer.android.com/google/play/billing/integrate...

**Comment by Mahadev-code** [comment] 2021-04-13 10:05
Use Billing Library above v-3

Demo application :- https://github.com/Mahadev-code/AndroidInAppPurchase

Source code tested on Google play store

**Comment by najam-amfnrh9** [comment] 2021-04-14 05:33
Thanks for your response...

**Comment by ashutoshgngwr** [comment] 2021-04-25 11:30
Duplicate of #478

**Comment by danieljr99048** [comment] 2021-04-28 15:26
trash

**Comment by danieljr99048** [comment] 2021-04-28 15:26
not work

**Comment by Cand3h** [comment] 2021-05-08 16:44
Any idea what to do? It seems that there won't be any update.

**Comment by TariqMahmud** [comment] 2021-07-22 05:44
> Source code tested on Google play store

will you not update this library?

**Comment by serggl** [comment] 2021-10-29 19:10
Library was upgraded. See https://github.com/anjlab/android-inapp-billing-v3/pull/497

**Closed by serggl** 2021-10-29 19:10 UTC
